apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./machine-management
  - ./node-feature-discovery/aggregate
  - ./node-maintenance-operator/aggregate
  - ./nvidia-gpu-operator/aggregate
  - ./openshift-virtualization/aggregate
