apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: openclaw
  namespace: openclaw
  labels:
    app: openclaw
spec:
  host: openclaw.gfontana.me
  to:
    kind: Service
    name: openclaw
    weight: 100
  port:
    targetPort: gateway
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
