apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../../../components/infra/node-maintenance-operator

patches:
  - target:
      kind: Subscription
      name: node-maintenance-operator
    path: patch-version.yaml
