apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../../../components/infra/nmstate

patches:
  - target:
      kind: Subscription
      name: kubernetes-nmstate-operator
    path: patch-version.yaml
