apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./cert-manager-certificates
  - ./cert-manager-operator/aggregate
#  - ./sealed-secrets-operator/operator --> Intentionally removed. Sealed Secrets are managed separately.
