apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./advanced-cluster-management/operator
  - ./mtv-operator/operator
  - ./openshift-ai/operator
  - ./openshift-gitops-operator/operator
  - ./openshift-image-registry/aggregate
  - ./openshift-pipelines/operator
