apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: homelab-monitoring

resources:
  - namespace.yaml
  - monitoringstack.yaml
  - ../../../../../../components/infra/homelab-monitoring
  - idrac-credentials-vault.yaml
  - unpoller-credentials-vault.yaml
  - pihole-credentials-vault.yaml
  - home-assistant-token-vault.yaml
  - scrapeconfig-idrac.yaml
  - scrapeconfig-home-assistant.yaml
  - scrapeconfig-lb.yaml
