apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../../../components/infra/cluster-observability-operator

patches:
  - target:
      kind: Subscription
      name: cluster-observability-operator
    path: patch-version.yaml
