apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openclaw

resources:
  - ../../../../components/apps/openclaw/base
  - openclaw-secrets-vault.yaml
  - route-ai.yaml

components:
  - ../../../../components/apps/openclaw/config

patches:
  - path: patch-route-host.yaml
  - path: patch-openclaw-json.yaml
  - path: patch-pvc-storageclass.yaml
