apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: truenas-nfs
  annotations:
    description: Provides RWX Filesystem volumes backed by TrueNAS NFS shares
provisioner: csi.truenas.io
parameters:
  protocol: nfs
  pool: pool1
  datasetPath: k8s/flanders/nfs
  compression: LZ4
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate
