apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../../../components/infra/kube-descheduler-operator

patches:
  - target:
      kind: Subscription
      name: cluster-kube-descheduler-operator
    path: patch-version.yaml
