apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: network-configuration
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  labels:
    gitops.ownedBy: default
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: gitops/clusters/simpsons/infra/network/configuration/
    repoURL: https://github.com/giofontana/gfontana-homelab.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
