apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  argocd.argoproj.io/sync-wave: "3"

resources:
  - ../operator
  - ../instance

patches:
  - target:
      kind: OdhDashboardConfig
      name: odh-dashboard-config
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-options
        value: "SkipDryRunOnMissingResource=true,ServerSideApply=true"
