apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../../../components/infra/node-feature-discovery

patches:
  - target:
      kind: Subscription
      name: nfd
    path: patch-version.yaml
