apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-data-foundation
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  labels:
    gitops.ownedBy: default
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  ignoreDifferences:
    - group: ocs.openshift.io
      kind: StorageCluster
      name: ocs-storagecluster
      namespace: openshift-storage
      jqPathExpressions:
        - .spec
    - group: console.openshift.io
      kind: ConsolePlugin
      name: odf-console
      jqPathExpressions:
        - .spec.proxy
        - .spec.i18n
  project: default
  source:
    path: gitops/clusters/simpsons/infra/storage/openshift-data-foundation/aggregate
    repoURL: https://github.com/giofontana/gfontana-homelab.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
