apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hashicorp-vault
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  labels:
    gitops.ownedBy: default
spec:
  destination:
    namespace: vault
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://helm.releases.hashicorp.com
      chart: vault
      targetRevision: 0.34.0
      helm:
        valueFiles:
          - $values/gitops/components/infra/hashicorp-vault/values.yaml
          - $values/gitops/clusters/simpsons/infra/security/hashicorp-vault/helm/values.yaml
    - repoURL: https://github.com/giofontana/gfontana-homelab.git
      targetRevision: main
      ref: values
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      name: hashicorp-vault-agent-injector-cfg
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
