apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps-network-flanders
  namespace: argocd-flanders
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  labels:
    gitops.ownedBy: default
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: gitops/clusters/flanders/infra/network/argocd-apps
    repoURL: https://github.com/giofontana/gfontana-homelab.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
