apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../../../components/infra/local-storage

patches:
  - target:
      kind: Subscription
      name: local-storage-operator
    path: patch-version.yaml
