apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bmc-test-credentials
  namespace: kubevirtbmc-demo
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: bmc-test-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: kubevirtbmc-demo/bmc-test
        property: username
    - secretKey: password
      remoteRef:
        key: kubevirtbmc-demo/bmc-test
        property: password
