apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 99-worker-enable-psi
  labels:
    machineconfiguration.openshift.io/role: worker
spec:
  kernelArguments:
    - psi=1
