apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openclaw
  namespace: argocd-flanders
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  labels:
    gitops.ownedBy: default
spec:
  destination:
    namespace: openclaw
    server: https://api.flanders.lab.gfontana.me:6443
  project: default
  source:
    path: gitops/clusters/flanders/apps/openclaw/
    repoURL: https://github.com/giofontana/gfontana-homelab.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
