apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../../../components/infra/advanced-cluster-management

#components:
#  - ../../components/advanced-cluster-management

patches:
  - target:
      kind: Subscription
      name: advanced-cluster-management
    path: patch-version.yaml